/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SyncTokenRouteImport } from './routes/sync.$token'
import { Route as ShareTokenRouteImport } from './routes/share.$token'
import { Route as DocIdRouteImport } from './routes/doc.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SyncTokenRoute = SyncTokenRouteImport.update({
  id: '/sync/$token',
  path: '/sync/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareTokenRoute = ShareTokenRouteImport.update({
  id: '/share/$token',
  path: '/share/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const DocIdRoute = DocIdRouteImport.update({
  id: '/doc/$id',
  path: '/doc/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/doc/$id': typeof DocIdRoute
  '/share/$token': typeof ShareTokenRoute
  '/sync/$token': typeof SyncTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/doc/$id': typeof DocIdRoute
  '/share/$token': typeof ShareTokenRoute
  '/sync/$token': typeof SyncTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/doc/$id': typeof DocIdRoute
  '/share/$token': typeof ShareTokenRoute
  '/sync/$token': typeof SyncTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/doc/$id' | '/share/$token' | '/sync/$token'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/doc/$id' | '/share/$token' | '/sync/$token'
  id: '__root__' | '/' | '/doc/$id' | '/share/$token' | '/sync/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocIdRoute: typeof DocIdRoute
  ShareTokenRoute: typeof ShareTokenRoute
  SyncTokenRoute: typeof SyncTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sync/$token': {
      id: '/sync/$token'
      path: '/sync/$token'
      fullPath: '/sync/$token'
      preLoaderRoute: typeof SyncTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/$token': {
      id: '/share/$token'
      path: '/share/$token'
      fullPath: '/share/$token'
      preLoaderRoute: typeof ShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doc/$id': {
      id: '/doc/$id'
      path: '/doc/$id'
      fullPath: '/doc/$id'
      preLoaderRoute: typeof DocIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocIdRoute: DocIdRoute,
  ShareTokenRoute: ShareTokenRoute,
  SyncTokenRoute: SyncTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
